In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from ipywidgets import interact, widgets
%matplotlib inline

In [2]:
## Read data files .asc
data = np.loadtxt("data1.asc")
#print(data)

df = pd.DataFrame(data, columns=['spatial1','spatial2','time','physical','intensity'])
#df

## Re-order the data based on the 'time' variable/dimension
dfo = df.sort_values('time', axis=0, ascending=True) 
dfo

       spatial1  spatial2      time  physical  intensity
8170       23.9      -0.6   0.00000  824.5855       42.0
5523       23.7      -1.7   0.00000  832.6115       17.0
12903      24.3       0.3   0.00000  832.6115       36.0
21797      25.2      -1.5   0.00000  832.6115       18.0
9181       24.0      -0.8   0.00000  832.6115       40.0
...         ...       ...       ...       ...        ...
5522       23.7      -1.8  28.90341  832.6115       17.0
3595       23.5      -1.1  28.90341  824.5855       33.0
15668      24.6      -0.5  28.90341  832.6115       46.0
9180       24.0      -0.9  28.90341  832.6115       40.0
15320      24.6      -1.3  28.90341  824.5855       25.0

[23717 rows x 5 columns]

In [3]:
# Show basic information
dfo.describe()

           spatial1      spatial2          time      physical     intensity
count  23717.000000  23717.000000  23717.000000  23717.000000  23717.000000
mean      24.251621     -0.774280     16.632241    835.218403    254.074925
std        0.635336      0.666822      3.485121     10.400502    306.864484
min       23.200000     -1.900000      0.000000    824.585500      1.000000
25%       23.700000     -1.400000     16.122010    824.585500     36.000000
50%       24.200000     -0.800000     16.702980    832.611500    109.000000
75%       24.800000     -0.200000     17.283950    849.589000    379.000000
max       25.300000      0.300000     28.903410    849.589000   1880.000000

In [5]:
# Import plotly.express as px
from mpl_toolkits import mplot3d

# Present the physical property using the size of points
# Put the other three variable in x, y, z axises 

# Put the time variable aside
# We can change the time option 
# to see the data at different time values
# Use 'interact' funtion to show the data

def plottime(time):
    dfo.sort_values(['physical'], inplace=True, ascending=False)
    Time = df.time == time
    area = df[Time].physical - 824 
    # since the values of 'physical' range from about 824 to 835,
    # the deduction of 824 helps to better visualize the variation
    
    fig = plt.figure(figsize = (9,9))
    #ax = fig.add_subplot(111, projection = '3d')
    ax = plt.axes(projection = '3d')
    
    ## Input those variable values
    x_vals = df[Time].spatial1 
    y_vals = df[Time].spatial2
    z_vals = df[Time].intensity
    
    ax.set_xlabel('spatial 1')
    ax.set_ylabel('spatial 2')
    ax.set_zlabel('intensity')
    
    ## Plot the values
    ax.scatter3D(x_vals, y_vals, z_vals, 
                 s = area, linewidth = 0.7, 
                 edgecolors = 'g');

    
interact(plottime, time=df['time'])

interactive(children=(Dropdown(description='time', options=(12.78141, 16.84822, 17.4292, 17.13871, 16.99347, 1â€¦